### ISSUE TITLE
Anonymize with hashing instead of initials

### ISSUE THREAD

**Issue by rtfeldman** [NoRedInk/take-home#14]
I mentioned this to @dui some time ago: suppose I know my friend Sam Quayle is applying, and I get assigned a take home for "SQ". Suddenly I have to worry about bias.

Would be nicer if I got assigned a take-home for "ac9bfg2" or something similar. :wink:

**Comment by dui** [comment]
I'm up for it! :+1: 

One problem is right now there isn't a straightforward way to link back to the candidate's profile from github for the hiring manager (in this case me) that prevents the evaluator (say you) from finding out who the candidate is.

I literally go to the list of candidates looking for the initials and click each to try and find out whether that's the right candidate

**Comment by eeue56** [comment]
@dui I could make it candidate/application ID? Then all you have to do is go to `https://app.greenhouse.io/people/<id>`

**Comment by rtfeldman** [comment]
:+1: for the ID-based approach!

**Comment by dui** [comment]
lovely! :heart_eyes:

**Comment by eeue56** [comment]
Done here - https://github.com/NoRedInk/take-home/commit/7c6fa755feeb6b6a639b2ef2a75a0ddf000d9935
