### ISSUE TITLE
Unclear and possibly misleading advice on Tasks

### ISSUE THREAD

**Issue by mietek** [NoRedInk/take-home#8]
Reading through [“Native best practices”](https://github.com/NoRedInk/take-home/wiki/Native-best-practices), I was confused by the following sections:

> _**Use always to ensure that your Tasks are wrapped appropriately.**_
> 
> _See https://github.com/elm-lang/core/issues/453#issuecomment-161050745_
>
> _**Denote impure functions with Task**_
>
> _There's no real way outside of `Tasks` to signify when a function is impure in Elm. Using units `()` to signify when a function should run and do something with a side effect allows people to easily identify side effects._
>
> ```elm
> activeElement : () -> Task x QueryNode
> activeElement =
>     Native.Query.activeElement
> ```

@rtfeldman points out that one may discover an incorrectly constructed `Task` by observing its behaviour in two scenarios:

1. When given as a parameter to `always`;
2. When suspended in an anonymous function that ignores its parameter.

(The latter idiom is known as `delay` in [Scheme](http://srfi.schemers.org/srfi-45/srfi-45.html), [SML](http://www.smlnj.org/doc/SMLofNJ/pages/susp.html) and [Idris](https://idris.readthedocs.org/en/v0.9.20.2/tutorial/typesfuns.html#laziness), as `lazy` in [OCaml](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Lazy.html), and as `defer` in [PureScript](https://github.com/purescript/purescript-lazy/blob/master/docs/Data/Lazy.md).)

I think this guide would benefit from an example of constructing a `Task` correctly, such as the one given in the linked discussion.

@jvoigtlaender gives the JavaScript part: (https://github.com/elm-lang/core/issues/453#issuecomment-161041092)
```javascript
const readFileAndLog = function (path) {
  return Task.asyncFunction(function (callback) {
    fs.readFile(path, function(err, data) {
      if (err) {
        throw err;
      } else {
        console.log("data: ", data);
      }
    });
    return callback(Task.succeed(Utils.Tuple0));
  });
};
```

@Fresheyeball gives the Elm part: (https://github.com/Fresheyeball/isolating-task-bug/blob/asyncFunction-solution/OK.elm)
```elm
readFileAndLog : String -> Task x ()
readFileAndLog = Native.FS.readFileAndLog
```

The advice to _“use_ [`()` as an additional parameter] _to signify when a function should run and do something with a side effect”_ seems misleading, if we assume that a `Task` already represents an effectful computation.

Thoughts?

**Comment by eeue56** [comment]
Sure. That bit of documentation is an old convention that isn't required any more. I've updated it to just recommend using tasks. 

Note that all this documentation is somewhat un-current and incomplete.

**Comment by mietek** [comment]
Nevertheless, this still appears to be the best available documentation…

**Comment by eeue56** [comment]
It's intentional :smile: See here - https://groups.google.com/forum/#!topic/elm-discuss/DPuUPv72abc

If you have any questions, feel free to ping me on slack and I'll try and help.
