### ISSUE TITLE
Get rid of Amazon

### ISSUE THREAD

**Issue by gyzerok** [NoRedInk/take-home#9]
It would be awesome if you can get rid of Amazon here so everyone can just run this to see how things works.

I know that you do not develop it for people as an example but it would be awesome if you'll find time to do this.

**Comment by gyzerok** [comment]
And yeah, I do really appreciate what you are doing guys! :+1:

**Comment by eeue56** [comment]
Maybe, I'll think about it. This is a production application, you don't need S3 to run it, it will run without it. It just won't fully function as a take-home server.
